### ISSUE TITLE
搜索结果页面的搜索框无法正确搜索

### ISSUE THREAD

**Issue by hyh19962008** [Gamuxorg/gamuX#13]
应该是输入框中的值没有正确传递给后台，一直是NULL

**Comment by shouhuanxiaoji** [comment]
情况是这样的，有两个搜索框，一个是侧边栏的，可以enter回车搜索，另一个是搜索页的，只能通过点击鼠标搜索

**Comment by shouhuanxiaoji** [comment]
出现这一问题，是由于两个搜索框互相无关联，是相互独立的。以后可能会改进

**Comment by hyh19962008** [comment]
已删除搜索结果页面的搜索框
